env:
  global:
    - secure: 'gqWyu9D4RRgNifNWzxuD9lecll93c/ogjQC7XgOjFN9vi83nElAUUV6r9NVga6Uv0RII0i1dZHee/aRNceYBw/MiaFpyPpy97u1ZgoPQv3/CdkmBxfESsBIV6/iMViouVUK97NSZE7mgq5yQjx1bJHyhY5XZZMKcuJkqiHZ2y7zLPs4i1ANNwd0qL5+v+rgQS+idQMEJTCPw9uYak/O1GjzvMokDKaRuU4SGk1QZhPDAlb+4b/wCkrvHbOzdPXl2w5v/n1rNXlDk7hxAH3JcFyQ3TVJKK4iRlSOizwqBiqZUJxVOVEf8LzaL/3/CiSQs9McSYdDPDtp0MC3fOGrbcSnTshHbumVMljiqOD/FHKNHuhuzF+OV5pxr+EIN29bfzeY14ZOH18llNLDotf8YMTkTjw7QqikiUnZYbccHYswWhpirRCAF6w1kvk58NAohFe9UO5NMeTPCkIokPoy3IFHALB9AGHAEQ5fzHzN3nbZWvbtPkjhH27yanfB9TUhW+mmKkv6pQJLuvuEdVW+c8EEyNmrwsXkqavOapf6u3WobwjkX44Zxpq8X0kVaJBS3UZuYTL0ytYS/t7I5GOh52BUfltkspYCwVGZ9oYG3uodWtZJWfELglGEWQMooUsP631WzpEjIRqGC6WJePG4Z/J4R91VOuQNNy6XsyE+jK2E='
    - secure: 'eQWCRyRGlshKHMp/jP1sDoNYXu1mrhqCLm2cAXe1lAeueLcM2BNKbl6hLqxBaux3sHIyIXsCv9gmmneeqSFXQN0uqMtqJjZkFyMpUkLJBFuyqR2k5uYza2QKoHWj5cQlMi5xEBg7b7OWdaTh+ZI6nQZuRYcElMKjO5d6gnNIgBLYYpnaxYfY3GY04JexkSNOOiSL3zyyxU7cZ2xbtyJ7HJEL6nN2jYqVXHhEM+1j7DBgHg7GP/h9Conh+z+8HfoS/nOyOJ23nyZeoycNFCe5JSbc3DBth1W+VY+wGNwf5ODGx1UMjU1lP4fFB1rCPDA0BiK4H9mEXGP5PG3EfG7iM9yjn52IZZE/xdJddireeA04GlWNnLIw0hU80xKKpuEOE3r8DeUlySjXgnLjXb5kQc0zYzo8muAYjb9rYuDptVVlR1SK2q0nM8Yh+m/eCt8Et6OoiKcJeH+pzVRLX8N7V/ngh//ha40KxyAxTTGWfM5sFk94kfnfQ6r3HhaSvAnZlFlnN6kHFjqProk4UKCRRsbv5Njo2Kvg+eW2ONNoMjdRoGk9khP+ncFNxF1hSCtsZE7amIBdbnDcvb6Xo7UBHoYFJMArYf7HYMf/hvRatK2cwgI09jMtTaL6s/XvDGynv8yizk+UR5OA9j7pygPp5qk0EsW9rqQsduq2ZIlwvwI='
    - secure: 'AVp47nMwTqddWGN77cdunRhi8Ruyhhv54fz7iU2W6zMPMGSx4Fm0EjnsaNcNdSqHu16q7/zxVqF+p/R7Dypi93pAuxns4Tjf9aG1CEOPiFd0uivRYKSEARB12ywP9k5H6pRg3EZQMRqJUsWYFPeUDlBD62PSMzQ231sYgy39/2V9uT/8incKQ39MrNH00WmSw4DXwMxSO0z/ButDp7WiyVjTT7uhk8VTo0sEbfPmZjKznACa6kG+9ND1OV65pKL/4zEAXA0wi9a56bIXMqSXU1BiHzenPHhQoTdqW6JnekyOuvG8CUsDpFRI5AHo7Z3Xkj6HLfHvdk1HmKT6Zb5OCHmTuhPN4JUm1xP/G1SrthL7qk1txWyUIN6ym6ck4oTkgqOtQxl5KErmxlxEquea615t9hzmQTuUYoclnZMnd2pawOwyeOcrLd3GDdSVRuLNMz7JrQShOkolIDtloXbYcRt+2mc15seC/0zRtgNYcWxpWxlVq8e9jOPmWHfOSEi33fghZbK7JC3xZ7AHjQg8UvMaLd8KOe8mJ5bXVc9ACeOSjEPNGyQyimM9g2E0PJnoTjD3zB6UBsajjmj639siPqFtwzmMgJfwrED++uVOC3Vp8b4u7542ras33RpXa3lT7+3ZJF9MfD7FIqNEX3t05YkvQXrdj/LBYC4fy+ZNab4='
jobs:
  include:
    - stage: android
      os: linux
      dist: xenial
      language: android
      jdk: openjdk8
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-29.0.3
          - build-tools-30.0.0
          - android-30
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-google_play_services
        licenses:
          - 'android-sdk-license-.+'
      before_install:
        - yes | sdkmanager "platforms;android-30"
        - openssl aes-256-cbc -K $encrypted_8107114604f7_key -iv $encrypted_8107114604f7_iv -in deploy/i8104/environment.prod.ts.enc -out src/environments/environment.prod.ts -d
        - openssl aes-256-cbc -K $encrypted_248d61edfafe_key -iv $encrypted_248d61edfafe_iv -in deploy/i8104/service_account.json.enc -out src/assets/data/service_account.json -d
        - openssl aes-256-cbc -K $encrypted_46bf629a46ce_key -iv $encrypted_46bf629a46ce_iv -in android/dist/i8104/environment.gradle.enc -out android/environment.gradle -d
      install:
        - nvm install 10
        - node --version
      before_script:
        - npm install -g @ionic/cli
        - npm ci
      script:
        - ionic build --prod
        - ionic cap sync android --prod
        - cd android
        - ./gradlew clean build
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_2da261b140f9_key -iv $encrypted_2da261b140f9_iv -in dist/i8104/googleplay-developer-key.json.enc -out dist/i8104/googleplay-developer-key.json -d
        - openssl aes-256-cbc -K $encrypted_f31a8877f884_key -iv $encrypted_f31a8877f884_iv -in dist/i8104/androidkey.jks.enc -out dist/i8104/androidkey.jks -d
        - gem install fastlane -N
      deploy:
        skip_cleanup: true
        provider: script
        script: >-
          APP_IDENTIFIER="it.casaricci.airborne.i8104"
          GOOGLE_PLAY_CREDENTIALS="dist/i8104/googleplay-developer-key.json"
          fastlane deploy_i8104
        on:
          branch: release

    - stage: ios
      os: osx
      osx_image: xcode12.2
      language: objective-c
      xcode_workspace: ios/App/App.xcworkspace
      xcode_scheme: App
      before_install:
        - nvm install 10
        - node --version
        - openssl aes-256-cbc -K $encrypted_8107114604f7_key -iv $encrypted_8107114604f7_iv -in deploy/i8104/environment.prod.ts.enc -out src/environments/environment.prod.ts -d
        - openssl aes-256-cbc -K $encrypted_248d61edfafe_key -iv $encrypted_248d61edfafe_iv -in deploy/i8104/service_account.json.enc -out src/assets/data/service_account.json -d
      before_script:
        - npm install -g @ionic/cli
        - npm ci
      script:
        - ionic build --prod
        - ionic cap sync ios --prod
