jobs:
  include:
    - stage: ionic
      language: node
      node_js:
        - '10.23.0'

      before_script:
        - npm install -g ionic
        - npm ci
      script:
        - ionic build --prod

    - stage: android
      language: android
      jdk: openjdk8
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-29.0.3
          - build-tools-30.0.0
          - android-30
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-google_play_services
        licenses:
          - 'android-sdk-license-.+'
      before_install:
        - yes | sdkmanager "platforms;android-30"
      script:
        - ./gradlew clean build
#      before_deploy:
#        - openssl aes-256-cbc -K $encrypted_022658120507_key -iv $encrypted_022658120507_iv -in dist/googleplay-developer-key.json.enc -out dist/googleplay-developer-key.json -d
#      deploy:
#        skip_cleanup: true
#        provider: script
#        script: ./gradlew publishInternal
#        on:
#          branch: release
