jobs:
  include:
    - stage: ionic_android
      os: linux
      dist: xenial
      language: node_js
      node_js:
        - '10.23.0'

      before_install:
        - openssl aes-256-cbc -K $encrypted_8107114604f7_key -iv $encrypted_8107114604f7_iv -in deploy/i8104/environment.prod.ts.enc -out src/environments/environment.prod.ts -d
        - openssl aes-256-cbc -K $encrypted_248d61edfafe_key -iv $encrypted_248d61edfafe_iv -in deploy/i8104/service_account.json.enc -out src/assets/data/service_account.json -d
      before_script:
        - npm install -g @ionic/cli
        - npm ci
      script:
        - ionic build --prod
        - ionic cap sync android --prod
      workspaces:
        create:
          name: ionic-android-output
          paths:
            - .

    - stage: android
      os: linux
      dist: xenial
      language: android
      jdk: openjdk8
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-29.0.3
          - build-tools-30.0.0
          - android-30
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-google_play_services
        licenses:
          - 'android-sdk-license-.+'
      workspaces:
        use: ionic-android-output
      before_install:
        - yes | sdkmanager "platforms;android-30"
        - openssl aes-256-cbc -K $encrypted_46bf629a46ce_key -iv $encrypted_46bf629a46ce_iv -in android/dist/i8104/environment.gradle.enc -out android/environment.gradle -d
      script:
        - cd android
        - ./gradlew clean build
#      before_deploy:
#        - openssl aes-256-cbc -K $encrypted_022658120507_key -iv $encrypted_022658120507_iv -in dist/googleplay-developer-key.json.enc -out dist/googleplay-developer-key.json -d
#      deploy:
#        skip_cleanup: true
#        provider: script
#        script: ./gradlew publishInternal
#        on:
#          branch: release

    - stage: ionic_ios
      os: osx
      osx_image: xcode12.2
      language: node_js
      node_js:
        - '10.23.0'

      before_install:
        - openssl aes-256-cbc -K $encrypted_8107114604f7_key -iv $encrypted_8107114604f7_iv -in deploy/i8104/environment.prod.ts.enc -out src/environments/environment.prod.ts -d
        - openssl aes-256-cbc -K $encrypted_248d61edfafe_key -iv $encrypted_248d61edfafe_iv -in deploy/i8104/service_account.json.enc -out src/assets/data/service_account.json -d
      before_script:
        - npm install -g @ionic/cli
        - npm ci
      script:
        - ionic build --prod
        - ionic cap sync ios --prod
      workspaces:
        create:
          name: ionic-ios-output
          paths:
            - .

    - stage: ios
      os: osx
      osx_image: xcode12.2
      language: objective-c
      workspaces:
        use: ionic-ios-output
      # TODO create stuff - before_install:
      xcode_workspace: ios/App/App.xcworkspace
