# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

setup_travis

default_platform(:ios)

platform :ios do
  desc "Deploy a new version to TestFlight"
  lane :deploy_i8104 do
    build_app(scheme: "Release (I-8104)",
              workspace: "App.xcworkspace",
              include_bitcode: true)
  end
end
