# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

setup_travis

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy_i8104 do
    gradle(task: "clean assemble",
           build_type: "release",
           properties: {
               "android.injected.signing.store.file" => Dir.pwd + "/../dist/i8104/androidkey.jks",
               "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"] ,
               "android.injected.signing.key.alias" => ENV["ANDROID_KEY_ALIAS"],
               "android.injected.signing.key.password" => ENV["ANDROID_KEY_PASSWORD"],
           },
           print_command: false)
    upload_to_play_store(
        track: 'internal',
        metadata_path: "fastlane/i8104")
  end
end
